### ISSUE TITLE
don't require exact timestamps in alerting data responses

### ISSUE THREAD

**Issue by Dieterbe** [raintank/worldping-api#37]
grafana alert executor has sanity checks for the returned data and looks for timestamps the way data was originally saved. but we've since added logic to MT to quantize all timestamps. and want to query MT. I think we can just remove this check from the executor and assume that the output returned by "graphite" (whether graphite-api or MT directly) is correct in that regard.

**Comment by Dieterbe** [comment]
why is this closed?

**Comment by woodsaj** [comment]
it was fixed 7months ago.  https://github.com/raintank/worldping-api/commit/2489ba7b4f93af4299ac9aae4186704b5d6e30e8

**Comment by woodsaj** [comment]
Actual a commit is https://github.com/raintank/worldping-api/commit/913a5406e9f695a9a3578d0f2b7e5769cbb29d5e
