### ISSUE TITLE
http 500 when proxied datasource is down

### ISSUE THREAD

**Issue by Dieterbe** [raintank/worldping-api#41]
if using a proxied datasource, and it is down, grafana will just return 500's but no http body, so in the grafana UI there's nothing we tell the user other than "internal server error"

also this appears in the log:

```
2016/04/28 19:06:53 http: proxy error: dial tcp 127.0.0.1:18764: getsockopt: connection refused
2016/04/28 19:06:53 [I] Completed 100.2.116.72 admin "POST /render HTTP/1.1" 500 Internal Server Error 0 bytes in 2634us
``
```

**Comment by woodsaj** [comment]
This sounds like a problem in Grafana, not worldping-api
