### ISSUE TITLE
API Call - Disable all monitors

### ISSUE THREAD

**Issue by mattttt** [raintank/worldping-api#64]
For folks that are exceeding the free tier, can someone whip me up a quick API call to go through and disable all monitors? Doing it manually through wp-admin is for the birds.

**Comment by mattttt** [comment]
@nopzor1200 had the good extension to the idea which is to also make this a big ol' button in Grafana.net that lets someone disable all of their own checks

**Comment by mattttt** [comment]
💯 Excited!

**Comment by woodsaj** [comment]
deployed.
