### ISSUE TITLE
sydney, new york and atlanta down ? 

### ISSUE THREAD

**Issue by jonathanleang** [raintank/worldping-api#74]
for these 2 location I got dial error. getsockopt: connection refused 
all other location connected just fine.

server is nginx re-proxy to phoenix/cowboy

<img width="676" alt="screen shot 2017-07-14 at 1 08 06 pm" src="https://user-images.githubusercontent.com/282017/28199099-83a31e6a-6895-11e7-8bd8-128baa152fdf.png">

**Comment by woodsaj** [comment]
these probe locations are all operating normally.  If you are ever in doubt, you can look at the "~google_com_demo" endpoint which is public data viewable to all users.

Given that multiple locations all reported an error at the same time, the probability that there is/was a problem on your server is extremely high.
